# Generated by Django 6.0.3 on 2026-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('not_started', '⚪ Не начато'), ('in_progress', '🟡 В процессе'), ('completed', '✅ Выполнено')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
